---

global:
  output: 'json'
  account: 'xxxxxxxxxxxx'

credentials:
  region: 'us-east-1'

  aws_access_key_id: 'XXXXXXXXXXXXXXXXXXXX'
  aws_secret_access_key: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  aws_session_token: ''

key:
  keyname: 'admin'
  pubkey: 'ssh-rsa xxxxx'
