---

awlan-server:
  protocol: 'HTTP'
  port: 3000
  healthcheckprotocol: 'HTTP'
  healthcheckport: 'traffic-port'
  healthcheckenabled: true
  healthythresholdcount: 2
  unhealthythresholdcount: 2
  healthchecktimeoutseconds: 2
  healthcheckintervalseconds: 10
  healthcheckpath: '/loadbalancer'
  matcher:
    httpcode: '200'
  targettype: 'instance'

awlan-server-int:
  protocol: 'HTTP'
  port: 3000
  healthcheckprotocol: 'HTTP'
  healthcheckport: 'traffic-port'
  healthcheckenabled: true
  healthythresholdcount: 2
  unhealthythresholdcount: 2
  healthchecktimeoutseconds: 2
  healthcheckintervalseconds: 10
  healthcheckpath: '/loadbalancer'
  matcher:
    httpcode: '200'
  targettype: 'instance'
